### ISSUE TITLE
Comentarios sobre las formulas

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/sbformula#1]
YPP: Tener cuidado cuando NOPH = 0. En esos casos YPP debe ser NA y no Inf.

SHI: Cuidar división por 0 en NOPH/NOPS*100. Si NOPS es 0 la función debe devolver NA.

RFR: Para calcular esto necesariamente tiene que haber VW, DMVD, DMVF, DMD, y DMF. Luego de verificar que estas 5 variables no son ni NA ni 0, calcular:
- Igual a 0 si no hay ni CRW ni NCRW.
- Con CRW si solo hay CRW.
- Con NCRW si solo hay NCRW.
- Con CRW + NCRW si hay las dos.

NRPP: Tener cuidado cuando NOPH = 0. En esos casos NRPP debe ser NA y no Inf.

DMRY: Calcular solo si DMD y DMF son mayores que 0.

DMFY: Calcular solo si DMVD y DMVF son mayores que 0.

DM: Calcular solo si DMD y DMF son mayores que 0.

BIOM: Falta multiplicar por 10 para convertir en tons/ha.

ACRW: Calcular solo si NOCR es mayor que 0.

**Comment by omarbenites** [comment]
Hola @reyzaguirre ,
 He re-actualizado y corregido varias partes del código.
En relación a las variables que son mayores que 0, el código lo he mantenido, pues en la tabla controlada ellos podrán apreciar esos errores (y de paso calcula los valores que si son mayores de 0 de dichos traits).
